apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- locust-master.yaml
- locust-worker.yaml
- locust-master-service.yaml

images:
- name: locustio/locust
  # change the image name to the one you created for the benchmark
  newName: us-central1-docker.pkg.dev/email2podcast/ishmeetss-locust-docker-repo/locust-image:LTF

replicas:
- name: locust-worker
  count: 7
- name: locust-master
  count: 1
