apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  labels:
    name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - image: locustio/locust
          name: locust-master
          # make sure this is the same as locust-worker.yaml and the task that you are testing.
          args: [ "-f", "/tasks/public_http_query.py",  "--master", "--class-picker"]
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
          resources:
            limits:
              cpu: "1.5"
              memory: 4Gi
            requests:
              cpu: "1.5"
              memory: 4Gi
