apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  labels:
    name: locust-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - image: locustio/locust
          name: locust-worker
          # make sure this is the same as locust-master.yaml and the task that you are testing.
          args: ["-f", "/tasks/public_http_query.py",  "--worker", "--master-host", "$(LOCUST_MASTER)"]
          env:
            - name: LOCUST_MASTER
              value: locust-master  
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "2"
              memory: 4Gi
  
